# trigger build
name: Build and Release Signal Bot XL

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags (e.g., v1.0.0) 
  

jobs:
  build:
    runs-on: windows-latest  # GitHub-hosted Windows runner

    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@b08ff587957b579b5a55d21fd28f63d7e10b9410
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@d6ebc25835d46a080edf7d8a53db5f361d8f59e4
        with:
          python-version: '3.11'  # Change if you use another version

      # 3. Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # 4. Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 5. Verify files (optional, useful for debugging)
      - name: List files
        run: dir

      # 6. Build the .exe with PyInstaller
      - name: Build .exe
        run: pyinstaller --onefile main.py

      - name: Create Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
            tag_name: v1.0.0
            name: Signal Bot XL v1.0.0
            files: dist/main.exe
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
