name: Release main.exe

on:
  release:
    types: [created]

jobs:
  release-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Set up Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build main.exe
        run: |
          pyinstaller --onefile main.py --name "main"

      - name: Upload main.exe to Release
        uses: softprops/action-gh-release@de2c0eb89ae2c0d6a8628f5657a2c8dc0d58a1dc
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
