name: Release main.exe

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release-build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Re-save ML model with compatible pickle protocol
        shell: cmd
        run: >
          python -c "import pickle;
          with open('ml_model.pkl','rb') as f: model=pickle.load(f);
          with open('ml_model.pkl','wb') as f: pickle.dump(model,f,protocol=4)"

      - name: Build main.exe
        shell: cmd
        run: pyinstaller --onefile --add-binary "ml_model.pkl;." main.py --name "main"

      - name: Upload main.exe to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/main.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
